name: mediamine-collection
services:
  collection-web-scraper-complete-scan:
    image: mediamine/collection-web-scraper:latest
    container_name: mediamine-collection-web-scraper-complete-scan
    environment:
      WORKFLOW: WORKFLOW_COMPLETE_SCAN
    volumes:
      - ./logs/complete-scan/:/usr/src/app/logs/
    restart: always
  collection-web-scraper-page-text-scan:
    image: mediamine/collection-web-scraper:latest
    container_name: mediamine-collection-web-scraper-page-text-scan
    environment:
      WORKFLOW: WORKFLOW_PAGE_TEXT_SCAN
    volumes:
      - ./logs/page-text-scan/:/usr/src/app/logs/
    restart: always
  collection-web-scraper-page-text-scan-v2:
    image: mediamine/collection-web-scraper:latest
    container_name: mediamine-collection-web-scraper-page-text-scan-v2
    environment:
      WORKFLOW: WORKFLOW_PAGE_TEXT_SCAN_V2
    volumes:
      - ./logs/page-text-scan-v2/:/usr/src/app/logs/
    restart: always
  collection-web-scraper-rss-scan:
    image: mediamine/collection-web-scraper:latest
    container_name: mediamine-collection-web-scraper-rss-scan
    environment:
      WORKFLOW: WORKFLOW_RSS_SCAN
    volumes:
      - ./logs/rss-scan/:/usr/src/app/logs/
    restart: always
