export const FEEDS_TO_IDS_COMPLETE_SCAN = 'FEEDS_TO_IDS_COMPLETE_SCAN';
export const FEEDS_TO_IDS_PAGE_TEXT_SCAN = 'FEEDS_TO_IDS_PAGE_TEXT_SCAN';

export const WORKFLOW = 'WORKFLOW';
export const WORKFLOW_COMPLETE_SCAN = 'WORKFLOW_COMPLETE_SCAN';
export const WORKFLOW_PAGE_TEXT_SCAN = 'WORKFLOW_PAGE_TEXT_SCAN';
